### ISSUE TITLE
Document preconditions _as_ preconditions of the functions they attend

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/libmarpa#106]
Sorry, one more element of this: document preconditions _as_ preconditions of the functions they attend (Sorry, I'm unable to avoid trimming the doc for this method in other ways):

> `Marpa_Rule_ID marpa_g_rule_new(Marpa_Grammar g, Marpa_Symbol_ID lhs_id, Marpa_Symbol_ID *rhs_ids, int length)`
>
> Returns a new rule in `g` with `lhs_id` as its LHS symbol and its RHS symbols in [`rhs_ids`, `rhs_ids+length`), or -2 if a precondition was violated.
> 
> - Precondition: `lhs_id` has not been used in `g` on the LHS of a sequence rule (MARPA_ERR_SEQUENCE_LHS_NOT_UNIQUE)
> - Precondition: No other rule in `g` directly reduces the same sequence of RHS symbols to the same LHS symbol (MARPA_ERR_DUPLICATE_RULE)

In general you can avoid documenting MANY preconditions on every “method” by making a blanket precondition statement: “All `Symbol_ID` arguments are required to be valid in the method's first argument.” (then you say that the valid symbols in a recognizer are those valid in the grammar it was constructed from, etc.) You also describe `marpa_g_symbol_new(g)` as returning a new valid symbol in `g`.

_Originally posted by @dabrahams in https://github.com/jeffreykegler/libmarpa/issues/79#issuecomment-1080020851_

**Comment by jeffreykegler** [comment]
I should look at this after I have closed #79.

**Comment by jeffreykegler** [comment]
In https://github.com/jeffreykegler/libmarpa/issues/79#issuecomment-1080021085, @dabrahams said "never mind", but I created this issue so that I could take a 2nd look after closing #79, which would require me to go through all the methods carefully.  I have done so.

The LIbmarpa doc's current ad hoc treatment of method preconditions is industry standard.  Attempting to improve on this risks getting into correctness-proving territory, which is a research area.  At this point the Libmarpa API document is unusually careful, and any more care risks a great price in readability, with no real net improvement in clarity for the programmer.

I will follow the literature, particularly watching how other API docs handle these matters.

**Comment by jeffreykegler** [comment]
Per https://github.com/jeffreykegler/libmarpa/issues/106#issuecomment-1203010438, I intend to take no action on this issue, because it is not clear what useful and cost-effective action is possible.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by dabrahams** [comment]
I'm fine with whatever you choose to do, but FWIW I think your rationale is flawed. Your approach is only “industry standard” for systems where usage errors are treated as recoverable conditions.  In general, they are not recoverable, and treating them as though they are can cause systems to behave unpredictably by masking bugs.  “Fail hard and fast when you can afford to check” is a different philosophy that tends to uncover bugs earlier in the development cycle.  In these systems, the conditions for correct usage are well-specified.  For example, most libraries providing dynamic arrays make out-of-bounds array indexing a precondition violation rather than pretending that it's just as likely to be an intentional programming technique.

There are plenty of libraries out there where preconditions are explicitly documented as such.  Everything in the C++ standard library and the Swift standard library is done that way.  Rust libraries appear to do it.  🤷‍♂️  This has absolutely nothing to do with correctness proving, as far as I can tell, except inasmuch as it gives a programmer the tools to know definitively whether she's following the rules in the use of a component.    Note that not every precondition can (reasonably) be checked, especially in an unsafe language like C, and it's especially important to document those, since the consequences of violating them is usually undefined behavior.

**Comment by jeffreykegler** [comment]
@dabrahams abrahams: I will admit to having read none of the 3 APIs you mention.  Would you recommend one of the three in particular?

**Comment by dabrahams** [comment]
I'd recommend https://www.boost.org/sgi/stl/, which is a precursor of much of what's in the C++ standard library.

**Comment by jeffreykegler** [comment]
I'll look into this, and see what I can take away for the Libmarpa API.  I don't usually keep research projects or "wish list" items in issues, but I'll keep this one open for the time being as a reminder.

**Comment by jeffreykegler** [comment]
After mulling over my plans, I realize that I am unlikely to get to this issue in the near future.  Therefore, in commit https://github.com/jeffreykegler/libmarpa/commit/3c05b447ca47e7818af78dc1e77c893fe3079d29, I added an note, based on the suggestion in https://github.com/jeffreykegler/libmarpa/issues/106#issuecomment-1203107094, to the "Futures" chapter in the API doc.  It will remind me to look at this issue.

With that, and absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/106#issuecomment-1209827072.
