### ISSUE TITLE
position = -1 in a progress report?

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#114]
After encountering an unexpected token, I'm printing out the rules in progress for the latest earley set, and seeing lots where the dot position is reported as -1.  What does that mean?

**Comment by jeffreykegler** [comment]
-1 is for a completion.  This has its disadvantages, but I went with this, because completions are special, and they would be hard to spot if you had to memorize rule lengths, and match these up with the positive integers in the output.  I experimented with the tradeoff in my own debugging, and found the special -1 marker for completions best.

**Comment by dabrahams** [comment]
So… maybe that should be in the documentation?

**Comment by jeffreykegler** [comment]
Not a bad idea. :-)

Seriously, thanks for catching all this stuff. Originally, I just wrote the API doc on the (explicitly stated) assumption that the reader was familiar with a higher-level interface, which in effect means Marpa::R2.  This was a start, but it's time to get beyond this restriction.

Eventually, the API doc needs to be reviewed and eliminate all assumptions about prior Marpa knowledge eliminated.  But that's for a later revision.

**Comment by jeffreykegler** [comment]
Fixed as of commit https://github.com/jeffreykegler/libmarpa/commit/5f488d2893b1fa5557f7ce07b7b7008d7fa0554d.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/114#issuecomment-1178186401.
