### ISSUE TITLE
How do you build this library?

### ISSUE THREAD

**Issue by mitchellwrosen** [jeffreykegler/libmarpa#124]
Hey, I couldn't figure out how to build this library :)

The `INSTALL` file says to run `make dist`, but that's not a target of the top-level `Makefile`. I'm sure I'm missing something.

Thanks!

**Comment by jeffreykegler** [comment]
You're right and that's a bug.  Sorry.

If you're still willing to put up with me: :-)

1. Use the "tested" branch.  The "master" branch is not quaranteed to be useful.  But the bug is also in the current tested branch, so
2. There are ac_dist and cm_dist targets, for Autoconf and CMake distributions respectively.  Use whichever you prefer.  There is also a "test" target which runs a small test suite.  Always do a "make clean" before any of these.

I am working as we speak on packaging the first official, stable release, at which point there should be actual releases you can grab.

**Comment by jeffreykegler** [comment]
I am leaving this issue open until I fix the bug.

**Comment by jeffreykegler** [comment]
Commit https://github.com/jeffreykegler/libmarpa/commit/445c1fe2b395dbb12c1f215903ab64a2aa7aeb09 is the fix, but at this point it is only in the 'master' branch.  I want to stabilize the API doc before merging it into 'tested'.

Once commit https://github.com/jeffreykegler/libmarpa/commit/445c1fe2b395dbb12c1f215903ab64a2aa7aeb09 is in the 'tested' branch, I will close this issue.

**Comment by jeffreykegler** [comment]
I started the close countdown on issue #90.  Once #90 is closed, I will test the fix to this issue with Marpa::R2 and, on success, merge with "tested" and start the close countdown for this issue.

**Comment by jeffreykegler** [comment]
I created an "issue90" branch and tested it with Marpa::R2.  All is OK.  Once issue #90 closes, I will merge "issue90" into the "tested" branch.

**Comment by jeffreykegler** [comment]
I have merged this fix into the "tested" branch.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/124#issuecomment-1252625572.
