### ISSUE TITLE
ISO C90 forbids mixed declarations and code -- worth fixing?

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#14]
gcc 4.9.2 caught these warning under cygwin

```
marpa.w: In function ‘ahm_tag_safe’:
marpa.w:16116:1: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
marpa.w: In function ‘marpa_b_new’:
marpa.w:10478:1: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
marpa.w:10596:1: warning: ISO C90 forbids mixed declarations and code [-Wpedantic]
```

The can be fixed by dropping `const` and declaring as variables before the code. Is this worth doing or keeping `const` is more important?

**Comment by jeffreykegler** [comment]
I believe these warnings only occur when debugging is enabled, and I like them because they tell me that it's on -- the flags can be easy to miss.  It's possible that I might forget that debugging is on, but with all these warnings that's not likely.  [ At this point, because of the nature of the Libmarpa repo, at this point, I always run the tests with debugging on. ]

**Comment by rns** [comment]
Ok, got it.
