### ISSUE TITLE
No documented way to get an error message

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#21]
Unless I'm missing something. :)

The `marpa_g_error()` doc says 

> When a method fails, this method allows the application to read the error code. p_error_string is reserved for use by the internals. Applications should set it to NULL.

There is marpa_error_description in marpa_codes.c, but do documented way to access it, AFAIK.

Or is it by design that the app must set up and use its own error messages based on those suggested in the doc?

**Comment by jeffreykegler** [comment]
For external purposes, Libmarpa does not deal in strings, except for the default "out of memory" message.  `p_error_string` was for debugging -- when I was evolving the error codes, I could make some errors a "catch all", and explain in the string.  When development was done, the strings were eliminated in favor of separate error codes.

The codes in `marpa_codes.c` are  suggested defaults, and inaccessible via Libmarpa's interface by design.  Kollos and Marpa::R2 both use them and you can look at them for examples of how you use `marpa_codes.c` in a real application.
