### ISSUE TITLE
valid/invalid vs. well-formed/malformed/not well-formed

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#29]
As applies to symbol/rule/assertion IDs. The method descriptions use the latter most of the time, while error code descriptions use the former.

Is this by design? If not, moving to valid/invalid everywhere seems to be more consistent.

**Comment by jeffreykegler** [comment]
The terms mean different things.  For example, symbol IDs must be
non-negative numbers, so that -1 is not a well-formed symbol ID.  42, on
the other hand, is a well-formed symbol ID, but there may be only 10
symbols, in which case 42 would not be a valid symbol ID.

**Comment by rns** [comment]
Thanks for explaining, it clear now: I just missed *_NO_SUCH_* error codes, which are for well-formed but invalid symbols/rules.

**Comment by jeffreykegler** [comment]
With the error mnemonics, there's an additional consideration.  As a
policy, mnemonics are not changed, even if they become (or were from the
outset) misleading or even false.  This is to preserve backward
compatibility in code.  So I made my first guess as to whether invalidity
was the issue, or only well-formedness , and stick with that guess even if
it turns out wrong.
