### ISSUE TITLE
marpa_g_force_valued() on failure

### ISSUE THREAD

**Issue by rns** [jeffreykegler/libmarpa#68]
`marpa_g_force_valued()` doc says just "On failure, a negative integer." 

This makes it unique in [error handling when wrapping](https://github.com/rns/libmarpa-bindings/blob/master/lua/libmarpa.lua#L752).

Its [code](https://github.com/jeffreykegler/libmarpa/blob/master/work/dev/marpa.w#L1379) returns -2 and sets MARPA_ERR_VALUED_IS_LOCKED error code on failure.

Perhaps change the doc to say `On failure, -2 and sets MARPA_ERR_VALUED_IS_LOCKED`? 

If yes, I'd gladly file a PR. On a related note: it wasn't tested on trivial grammar; does it need to be?

**Comment by jeffreykegler** [comment]
Right now the Kollos version of Libmarpa is an identical copy.  Any change and I either recopy, or we have forked Libmarpa.  So I'd like to drag my feet on this one.

Re its actual merits, I'll have to look into it, but on a quick reading it seems like a good idea.

**Comment by jeffreykegler** [comment]
In future versions, `marpa_g_force_valued()` will be eliminated, along with the entire valued vs. unvalued feature.  I'll leave this issue open until that is done.

**Comment by whitten** [comment]
Why did you decide to eliminate marpa_g_force_valued() rather than change it as rns suggested?
What does the valued vs. unvalued feature actually do?
Is there a way to do that without the valued vs. unvalued feature ?

**Comment by jeffreykegler** [comment]
The ability to have "unvalued" tokens was an efficiency hack.  I found it
somewhere between useless and counter-productive and AFAICT nobody else has
ever tried to use it.  The purpose of the `marpa_g_force_valued()` is to
turn this hack off.  This is what the SLIF does, and the SLIF is how almost
everybody uses Libmarpa.

Once "unvalued" tokens are elminated.  There will be no need to force
tokens to be valued, and no need for a `marpa_g_force_valued()` call.

**Comment by jeffreykegler** [comment]
After thinking it over, I think a fix is appropriate and that the fix is the change suggested by @rns in https://github.com/jeffreykegler/libmarpa/issues/68#issue-79302917 all those years ago.  Accordingly, I am reclassifying this as a doc fix, to be carried out when I do a group of doc fixes together.  (Hopefully, getting to these will not take me the better half of a decade!)

**Comment by jeffreykegler** [comment]
Fixed in commit https://github.com/jeffreykegler/libmarpa/commit/67a9883e3b8f2f3eca3f16541abb5743d7580cdb -- the change may be checked at http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/latest/index.html#Grammar-constructor.  Absent feedback to the contrary, I will close this issue in a week or so.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/68#issuecomment-1108856465.
