### ISSUE TITLE
Fail to build libmarpa using CMake

### ISSUE THREAD

**Issue by tan-wei** [jeffreykegler/libmarpa#70]
Currently, I build `libmarpa` in the directory `build`.
Some information:
  - libmarpa: latest git master branch
  - CMake 3.15.4
  - MSVC 10.9.24

Output:
```console
λ cmake ..\cmake
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.24.28314.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for inline
-- Looking for inline - found
-- Checking if NULL == 0
-- Checking if NULL == 0 - yes
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Configuring done
CMake Error at CMakeLists.txt:91 (ADD_LIBRARY):
  Cannot find source file:

    marpa.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:91 (ADD_LIBRARY):
  No SOURCES given to target: marpa


CMake Error at CMakeLists.txt:92 (ADD_LIBRARY):
  No SOURCES given to target: marpa_s


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by jeffreykegler** [comment]
https://colabti.org/irclogger/irclogger_log/marpa?date=2019-12-29#l1

I alerted our IRC channel to this issue.  I don't run any MS OS, and the Microsoft build comes from other volunteers.

A lot of people are offline due to the holidays, so I will wait until next week and alert the IRC channel again then.

**Comment by tan-wei** [comment]
Thanks for your rapid reply. I'll wait for the patches.
BTW, thanks for this great project.

**Comment by jeffreykegler** [comment]
I'll go back to the IRC channel on this in the coming week.

The complaint is about a missing marpa.c file.  Is it really missing?  Or is there a naming issue?

The Microsoft support has always been on the basis that those who want it maintain it and I just do upstream stuff -- Microsoft support only exists because someone long ago took the trouble to make sure my C code compiled on Microsoft.  My perception is that some of the original volunteers have lost interest, but we will find out.

If the worst happens, and a Marpa-Microsoft community does not come forward, as a desperate last measure, I will take this on, but I will only do sanity checks under Linux.  If, as is quite probable, no issue appears that I can deal with under Linux, then I will close this issue without a fix, and the documentation will be updated to reflect lack of Microsoft support.  Right now I'm working on a paper on Marpa, and I'd tackle this issue after I finish it.

Hoping for the best on this, jeffrey.

**Comment by tan-wei** [comment]
Thanks very much.

**Comment by jeffreykegler** [comment]
I'd hoped to finish a paper I was working on and then move on to this, but the paper is taking longer than expected, so I've moved this to the front of the queue.

**Comment by jeffreykegler** [comment]
I can do a cmake build successfully under Linux with the following commands:

cd libmarpa_repo
make clean
make dists
cd ..
mkdir build
cd build
cmake ../libmarpa_repo/cm_dist
cmake --build .

@tan-wei I don't know if this helps you at all.  I don't have access to any Microsoft environment and, if this doesn't point the way to a solution to your problem, my next step will be to go to the IRC channel and see if anyone is interested in supporting these environments.  (In the past, people have used Windows, and been willing to do some volunteer work, but I'm not sure if anyone is using Windows now.)

**Comment by tan-wei** [comment]
Thanks for your reply. But I still have some questions before try the commands under Linux, since I must install a Linux machine.

The error messages from CMake complain that source code file `marpa.c` is missing, I can't find in the repo, either. I find the commands you give me inculdes `make dists`. Does it mean that `marpa.c` is generated by `make dists`? If yes, I think it's clear for me why I fail to compile it.

Thanks!

**Comment by jeffreykegler** [comment]
Yes, `marpa.c` is a created file, and will not exist unless `make dists` is run.  (I used "literate programming" and `marpa.c` is produced by Don Knuth's Cweb.) If you have not been running `make dists`, that would certainly explain the problem.  Perhaps now you'll be able to get it working under Windows.

**Comment by tan-wei** [comment]
Thanks, quite clear for me.
Let me try it on Linux first. After a successfully try, I will close this issue.
