### ISSUE TITLE
proper separation flag?

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#76]
> marpa_g_rule_is_proper_separation() succeeds if and only if rule_id is valid. If rule rule_id is a sequence rule where the proper separation flag is set, returns 1. 

What is this flag, and how is it set?  Doesn't seem to be documented anywhere.

**Comment by jeffreykegler** [comment]
The concept of proper separation is documented under `marpa_g_sequence_new()`: 

> If `flags & MARPA_PROPER_SEPARATION` is non-zero, separation is “proper”, that is, a trailing separator is not allowed. The term proper is based on the idea that properly-speaking, separators should actually separate items.

What is your advice about what to do here?

The API doc does not try to be a tutorial and assumes some familiarity with some higher level interface, which has in practice meant the Perl interface.  However at points I do beyond and get slightly tutorial-ish, as in the `marpa_g_sequence_new()` `MARPA_PROPER_SEPARATION` description.

Btw, the contrasting term in the higher level docs, to describe separation that allows trailing separators, is "Perl separation", because that's the language in which I first encountered this style of separation.

**Comment by jeffreykegler** [comment]
Incidentally, helpful for searching the API is [this link](http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/stable/api_one_page.html), where the HTML is single-page.  This is one of many cases where my judgement was proven wrong by a Marpa adaptor.  I decided that supporting a one-page HTML was too much trouble, and suggested to a user that wanted it, that they could do it themselves.  They did, I would up using their web site more than my own for the API, and I relented.

**Comment by dabrahams** [comment]
That's actually where I was searching for the phrase "proper separation" and not finding it anywhere but in the docs for marpa_g_rule_is_proper_separation().  I realize now if I had searched for separate words I'd have found it.

I would retire the multi-page HTML if I were you, but it's your call.

**Comment by jeffreykegler** [comment]
Not much would be lost if the multi-page version were gone, I admit, but sometimes I found bouncing around among short pages preferable.  And I prefer, in the absence of bugs, to err on the side of conservatism, so I believe I will keep the status quo.
