### ISSUE TITLE
Consider renaming the generated `inc/` directory to `include/`.

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#77]
My homebrew formula works around this non-standardism by explicitly renaming the directory; it's a small point of friction that I had to work around.

**Comment by jeffreykegler** [comment]
I need a little more context here.  Are you saying my installation creates a non-standard directory?

**Comment by dabrahams** [comment]
I mean that in most environments, headers are installed in a directory called `include/` next to the directory called `lib/` where library binaries are installed; that's sorta standard.  Your distribution calls the directory containing headers `inc/`, which is sorta non-standard.

**Comment by whitten** [comment]
Could you give an example of another distribution that uses ./include/ instead if ./inc/ ?

**Comment by dabrahams** [comment]
What distribution _doesn't_ use `./include/`?  https://github.com/gcc-mirror/gcc/tree/master/include, https://github.com/llvm/llvm-project/tree/main/llvm/include, https://github.com/postgres/postgres/tree/master/src/include, …

**Comment by jeffreykegler** [comment]
I did a census on my system and, according to that, "inc" is only used in the Perl world.  Since libmarpa is supposed to hide, as much as reasonable, its Perl origins, this means that my use of "inc" instead of "include" is a mistake, if not a severe one.

Is it worth fixing, giving all the downstream changes it would inflict?  Ordinarily no, but perhaps fortuitously, I need to refresh myself on the libmarpa and Marpa::R2 build procedures in order to test and evaluate other changes, and this is a nice "test" change, one which arguably is an actual improvement, for me to use to re-familiarize myself.

**Comment by jeffreykegler** [comment]
This change is incorporated into the master branch as of https://github.com/jeffreykegler/libmarpa/commit/11089b107d46acdf93a41baee37e530f2401a410.  Absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
Closed for the reason given in https://github.com/jeffreykegler/libmarpa/issues/77#issuecomment-1098258140.
