### ISSUE TITLE
"Sets the error code" is vague

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#82]
http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/stable/api_one_page.html#Return-values says that a failure ”sets the error code,“ but it doesn't say where.  It _appears_ that this code is the code associated with the grammar being operated on, or the grammar that is the ultimate source of whatever object *is* the target of the method.  Whatever the actual case is, it should be made clear.

**Comment by jeffreykegler** [comment]
Good point.  I will fix this.

**Comment by jeffreykegler** [comment]
Fixed in the process of working on #79.  The html can be seen at http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/latest/index.html#Error-codes. The whole discussion of failure and error codes got an extensive rewrite, and the method descriptions are now being rewritten accordingly.

Absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/libmarpa/issues/82#issuecomment-1120409066.
