### ISSUE TITLE
Missing unrefs

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#88]
I just found this in the “nits” test:

```c
  /* re-create the recce and try some input */
  r = marpa_r_new (g);
```

Might be good to audit for missing unrefs.

**Comment by jeffreykegler** [comment]
I am much more careful about memory leaks than is fashionable.  The code involving unrefs was carefully constructed, with the possibility of missing unrefs systematically checked for.  In addition, the Marpa team has run valgrind several times, including since the last work on the unrefs and since the last code change of any size.  Our user base is leak-sensitive and aware that we treat leaks as serious bugs, contrary to much regrettable modern practice.  None of these fallback measures has ever found a memory leak in libmarpa since the release of Marpa::R2, though I have found them in previous Marpa packages, and did find one (now fixed) in the Perl code for Marpa::R2, which is less carefully checked.

Unless there is some specific reason to think there actually is a memory leak in libmarpa, I'd like to close this issue.

**Comment by dabrahams** [comment]
It's not a leak in libMarpa itself, but in its tests.

**Comment by jeffreykegler** [comment]
I'll give it a look.  Since I have pointed to the tests as examples, avoidance of bad practices might be in order.

**Comment by jeffreykegler** [comment]
Closed for the reason given in https://github.com/jeffreykegler/libmarpa/issues/88#issuecomment-1098260535.
